language: python
dist: xenial
sudo: false
evn:
  global:
    - secure: FxQsoberKXawRGE7NtUYRA
  matrix:
    - USE_NETWORK: true
python:
  - "3.6"
  - "3.7"
  - "pypy"
  - "pypy3"
install:
  - "pip install -r requirements.txt"
script:
  - pytest
